name: Nightwatch Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test-nightwatch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Nightwatch tests
        run: npm run nightwatch

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: reports/  # Adjust this to match the directory where Nightwatch generates test reports
